server:
  port: 8886

spring:
  application:
    name: jcode
#  mvc:
#    static-path-pattern: /res/**
  datasource:
    name: dmdb
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.98.138.165:3306/smart_meter?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: QingHong123!@#
  #devtools热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker: #freemarker配置
    allow-request-override: false # 是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
    allow-session-override: false # 是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性。
    cache: false # 是否启用模板缓存。
    charset: UTF-8 # 模板编码。
    check-template-location: true # 是否检查模板位置是否存在。
    content-type: text/html # Content-Type value.
    enabled: true # 是否启用freemarker
    expose-request-attributes: false # 设定所有request的属性在merge到模板的时候，是否要都添加到model中.
    expose-session-attributes: false # 是否在merge模板的时候，将HttpSession属性都添加到model中
    expose-spring-macro-helpers: true # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    prefer-file-system-access: true # 是否优先从文件系统加载template，以支持热加载，默认为true
    settings: # 设定FreeMarker keys.
      classic_compatible: true
      default_encoding: UTF-8
      template_update_delay: 0
    suffix: .ftl # 设定模板的后缀.
    template-loader-path: classpath:/templates/ # 设定模板的加载路径，多个以逗号分隔，默认:
#mybatis:
#  #mapperLocations: classpath:mapper/*.xml
#  type-aliase-package: com.haiot.springboot.entities

jcode:
  filepath:
    resources: D:\CodeSpace\JCode\src\main\resources


